<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('jemisys_store_mirror', function (Blueprint $table) {
            $table->id();

            $table->string('StoreCode', 20);
            $table->string('Description', 50)->nullable();
            $table->string('CompanyCode', 10);
            $table->string('GSTNo', 20)->nullable();
            $table->string('RegNo', 20)->nullable();
            $table->string('Address1', 50)->nullable();
            $table->string('Address2', 50)->nullable();
            $table->string('Address3', 50)->nullable();
            $table->string('Address4', 50)->nullable();
            $table->string('State', 50)->nullable();
            $table->string('PinCode', 20)->nullable();
            $table->string('Telephone', 20)->nullable();
            $table->string('Fax', 20)->nullable();
            $table->string('Message1', 50)->nullable();
            $table->string('Message2', 50)->nullable();
            $table->string('SalesInvoicePrefix', 2);
            $table->decimal('SalesInvoiceNoStart', 18, 0);
            $table->decimal('SalesInvoiceNoNext', 18, 0);
            $table->tinyInteger('SalesInvoiceLength');
            $table->string('SalesInvoicePrefix2', 2);
            $table->decimal('SalesInvoiceNoStart2', 18, 0);
            $table->decimal('SalesInvoiceNoNext2', 18, 0);
            $table->tinyInteger('SalesInvoiceLength2');
            $table->string('SalesReturnPrefix', 2);
            $table->decimal('SalesReturnStart', 18, 0);
            $table->decimal('SalesReturnNext', 18, 0);
            $table->tinyInteger('SalesReturnLength');
            $table->string('SalesReturnPrefix2', 2);
            $table->decimal('SalesReturnStart2', 18, 0);
            $table->decimal('SalesReturnNext2', 18, 0);
            $table->tinyInteger('SalesReturnLength2');
            $table->string('TradeInPrefix', 2);
            $table->decimal('TradeInStart', 18, 0);
            $table->decimal('TradeInNext', 18, 0);
            $table->tinyInteger('TradeInLength');
            $table->string('ReservePrefix', 10);
            $table->decimal('ReserveStart', 18, 0);
            $table->decimal('ReserveNext', 18, 0);
            $table->tinyInteger('ReserveLength');
            $table->string('JobOrderPrefix', 2);
            $table->decimal('JobOrderStart', 18, 0);
            $table->decimal('JobOrderNext', 18, 0);
            $table->tinyInteger('JobOrderLength');
            $table->string('DOPrefix', 50);
            $table->decimal('DONoStart', 18, 0);
            $table->decimal('DONoNext', 18, 0);
            $table->tinyInteger('DOLength');
            $table->string('FGStockOutPrefix', 2);
            $table->decimal('FGStockOutStart', 18, 0);
            $table->decimal('FGStockOutNext', 18, 0);
            $table->tinyInteger('FGStockOutLength');
            $table->string('FGLoanPrefix', 2);
            $table->decimal('FGLoanStart', 18, 0);
            $table->decimal('FGLoanNext', 18, 0);
            $table->tinyInteger('FGLoanLength');
            $table->string('GCPrefix', 2);
            $table->decimal('GCStart', 18, 0);
            $table->decimal('GCNext', 18, 0);
            $table->tinyInteger('GCLength');
            $table->boolean('IsRemote');
            $table->boolean('IsRetail');
            $table->boolean('IsFranchise');
            $table->string('CurrCode', 10);
            $table->decimal('ExchRateListing', 12, 6);
            $table->decimal('ExchRateAccount', 12, 6);
            $table->string('MemberType', 10);
            $table->boolean('IsGSTRegistered');
            $table->boolean('IsGSTInclusive');
            $table->boolean('Active');
            $table->smallInteger('OrderOfDisplay');
            $table->string('CreatedBy', 20)->nullable();
            $table->dateTime('CreatedDate');
            $table->string('ModifiedBy', 20)->nullable();
            $table->dateTime('ModifiedDate');
            $table->string('SalesGLCode', 10)->nullable();
            $table->string('CMOPrefix', 2);
            $table->decimal('CMOStart', 18, 0);
            $table->decimal('CMONext', 18, 0);
            $table->tinyInteger('CMOLength');
            $table->string('ExpPrefix', 2);
            $table->decimal('ExpStart', 18, 0);
            $table->decimal('ExpNext', 18, 0);
            $table->tinyInteger('ExpLength');
            $table->string('CSPrefix', 2);
            $table->decimal('CSStart', 18, 0);
            $table->decimal('CSNext', 18, 0);
            $table->tinyInteger('CSLength');
            $table->string('PrivateKey', 200)->nullable();
            $table->string('PublicKey', 200)->nullable();
            $table->string('RMTRPrefix', 2);
            $table->decimal('RMTRStart', 18, 0);
            $table->decimal('RMTRNext', 18, 0);
            $table->tinyInteger('RMTRLength');
            $table->string('FGTRPrefix', 2);
            $table->decimal('FGTRStart', 18, 0);
            $table->decimal('FGTRNext', 18, 0);
            $table->tinyInteger('FGTRLength');
            $table->string('POSOrderPrefix', 2);
            $table->decimal('POSOrderStart', 18, 0);
            $table->decimal('POSOrderNext', 18, 0);
            $table->tinyInteger('POSOrderLength');
            $table->string('EMail1', 50)->nullable();
            $table->string('EMail2', 50)->nullable();
            $table->string('EMail3', 50)->nullable();
            $table->string('EMail4', 50)->nullable();
            $table->string('EMail5', 50)->nullable();
            $table->string('GSTGLCode', 10)->nullable();
            $table->string('GMSGLCode', 10)->nullable();
            $table->string('DepositGLCode', 10)->nullable();
            $table->string('JOGLCode', 10)->nullable();
            $table->string('GiftCardGLCode', 10)->nullable();
            $table->string('WSSIPrefix', 2);
            $table->decimal('WSSIStart', 18, 0);
            $table->decimal('WSSINext', 18, 0);
            $table->tinyInteger('WSSILength');
            $table->string('WSCNPrefix', 2);
            $table->decimal('WSCNStart', 18, 0);
            $table->decimal('WSCNNext', 18, 0);
            $table->tinyInteger('WSCNLength');
            $table->string('WSCIPrefix', 2);
            $table->decimal('WSCIStart', 18, 0);
            $table->decimal('WSCINext', 18, 0);
            $table->tinyInteger('WSCILength');
            $table->string('WSCRPrefix', 2);
            $table->decimal('WSCRStart', 18, 0);
            $table->decimal('WSCRNext', 18, 0);
            $table->tinyInteger('WSCRLength');
            $table->string('GSTAbsorb', 1);
            $table->string('GVPrefix', 2);
            $table->decimal('GVStart', 18, 0);
            $table->decimal('GVNext', 18, 0);
            $table->tinyInteger('GVLength');
            $table->string('WSRPPrefix', 2);
            $table->decimal('WSRPStart', 18, 0);
            $table->decimal('WSRPNext', 18, 0);
            $table->tinyInteger('WSRPLength');
            $table->string('DRPrefix', 2);
            $table->decimal('DRNoStart', 18, 0);
            $table->decimal('DRNoNext', 18, 0);
            $table->tinyInteger('DRLength');
            $table->string('GiftVoucherGLCode', 10)->nullable();
            $table->string('CashTransferPrefix', 2);
            $table->integer('CashTransferStart');
            $table->integer('CashTransferNext');
            $table->tinyInteger('CashTransferLength');
            $table->string('CashAdjPrefix', 2);
            $table->integer('CashAdjStart');
            $table->integer('CashAdjNext');
            $table->tinyInteger('CashAdjLength');
            $table->integer('TillID');
            $table->decimal('MinCash', 19, 4);
            $table->decimal('MaxCash', 19, 4);
            $table->string('TaxCode', 20)->nullable();
            $table->boolean('IsLinkPoints');
            $table->decimal('IdealGoldWeight916', 18, 3);
            $table->dateTime('PromoDateFrom')->nullable();
            $table->dateTime('PromoDateTo')->nullable();
            $table->boolean('PromoSun');
            $table->boolean('PromoMon');
            $table->boolean('PromoTue');
            $table->boolean('PromoWed');
            $table->boolean('PromoThu');
            $table->boolean('PromoFri');
            $table->boolean('PromoSat');
            $table->string('ASPrefix', 2);
            $table->decimal('ASNoStart', 18, 0);
            $table->decimal('ASNoNext', 18, 0);
            $table->tinyInteger('ASLength');
            $table->string('LinkPoints', 2)->nullable();
            $table->string('LinkPointsDesc', 200)->nullable();
            $table->string('SalesGLCode_Gold', 20);
            $table->string('SalesGLCode_GMS', 20);
            $table->string('SalesGLCode_IPM', 20);
            $table->string('TRPrefix', 2);
            $table->decimal('TRNoStart', 18, 0);
            $table->decimal('TRNoNext', 18, 0);
            $table->tinyInteger('TRLength');
            $table->boolean('PrintImage_Invoice');
            $table->boolean('CashControl_Visible');
            $table->string('FAS_CostCentre', 20);
            $table->string('TDPrefix', 2);
            $table->decimal('TDNoStart', 18, 0);
            $table->decimal('TDNoNext', 18, 0);
            $table->tinyInteger('TDLength');
            $table->string('GSTAbsorb_RoundingMethod', 1);
            $table->decimal('IdealJewel', 19, 4);
            $table->string('CCPrefix', 2);
            $table->decimal('CCNoStart', 18, 0);
            $table->decimal('CCNoNext', 18, 0);
            $table->tinyInteger('CCLength');
            $table->string('CCGLCode', 20);
            $table->string('CCGLCode_Ser', 20);
            $table->string('CCGLCode_Pen', 20);
            $table->string('SalesInvoiceDPPrefix', 2);
            $table->decimal('SalesInvoiceNoDPNext', 18, 0);
            $table->tinyInteger('SalesInvoiceDPLength');
            $table->string('SalesInvoiceJOPrefix', 2);
            $table->decimal('SalesInvoiceNoJONext', 18, 0);
            $table->tinyInteger('SalesInvoiceJOLength');
            $table->boolean('IsParent');
            $table->decimal('CashFloatRounding', 19, 4);
            $table->string('TransferGLCode', 20);
            $table->string('TransferGLCode2', 20);
            $table->string('WSDNPrefix', 2);
            $table->decimal('WSDNStart', 18, 0);
            $table->decimal('WSDNNext', 18, 0);
            $table->tinyInteger('WSDNLength');
            $table->string('WSProPrefix', 2);
            $table->decimal('WSProStart', 18, 0);
            $table->decimal('WSProNext', 18, 0);
            $table->tinyInteger('WSProLength');
            $table->boolean('DP2Sales_After_PaymentReceived');
            $table->string('DEPrefix', 2);
            $table->decimal('DENoStart', 18, 0);
            $table->decimal('DENoNext', 18, 0);
            $table->tinyInteger('DELength');
            $table->string('CreditSalesGLCode', 20);
            $table->string('VTPrefix', 2);
            $table->decimal('VTNoNext', 18, 0);
            $table->tinyInteger('VTLength');
            $table->decimal('TradeInCeliling', 19, 4);
            $table->decimal('TradeInCeiling', 19, 4);
            $table->dateTime('OpeningTime')->nullable();
            $table->dateTime('ClosingTime')->nullable();
            $table->string('GSTAbsorb_GoldType', 500)->nullable();
            $table->string('GSTAbsorb_Category_Exclude', 500)->nullable();
            $table->string('GSTAbsorb_DesignCode', 100)->nullable();
            $table->string('GSTAbsorb_DesignName_Exclude', 200)->nullable();
            $table->string('DOPrefix2', 2);
            $table->decimal('DONoStart2', 18, 0);
            $table->decimal('DONoNext2', 18, 0);
            $table->tinyInteger('DOLength2');
            $table->string('eSignature_ApplicablePrograms', 100)->nullable();
            $table->decimal('PromoDiscount', 5, 2);
            $table->string('PromoMessage', 100)->nullable();
            $table->string('GSTAbsorb_Promotion_Exclude', 500)->nullable();
            $table->string('GSTAbsorb_SalesType', 10)->nullable();
            $table->string('GSTAbsorb_PointsRedemption', 1);
            $table->string('POSTrafficPrefix', 2);
            $table->decimal('POSTrafficNext', 18, 0);
            $table->tinyInteger('POSTrafficLength');
            $table->string('DepositGSTGLCode', 20)->nullable();
            $table->string('EMail', 50)->nullable();
            $table->string('EMail_Password', 50)->nullable();
            $table->boolean('SameDay_Exchange');
            $table->boolean('IsOnlineStore');
            $table->string('RO1', 20);
            $table->string('RO2', 20);
            $table->string('RO3', 20);
            $table->string('OldInventoryPrefix', 1);

            $table->timestamp('synced_at');

            $table->unique('StoreCode');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('jemisys_store_mirror');
    }
};
